added better config for linux, addpath, renamed git in the path to remove make errors etc

diff --git a/scripts/.local/share/scripts/utilities/nvim/vw b/scripts/.local/share/scripts/utilities/nvim/vw
--- a/scripts/.local/share/scripts/utilities/nvim/vw
+++ b/scripts/.local/share/scripts/utilities/nvim/vw
@@ -3,4 +3,8 @@ if [[ -z "$(command -v "$1")" ]]; then
     echo "$1 is not a script"
     exit
 fi
+if ! which "$1" &>/dev/null; then
+  echo "script not found"
+  exit 1
+fi
 nvim "$(which "$1")"
